#server:
# port: 8080
#
#
#spring:
#  datasource:
#    url: jdbc:mysql://localhost:3306/projecttimesheet
#    username: root
#    password: password
#    driverClassName: com.mysql.jdbc.Driver
#  jpa:
#    hibernate:
#     ddl-auto: update
